# Kafka Topic - Test
#
# Usage:
#   kubectl apply -f kafka-topic.yaml -n kafka

apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: test-topic
  labels:
    strimzi.io/cluster: dev-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: "3600000"
